name: Scheduler Job

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: echo "The server time is $(date)"
